import type { Accreditation } from '../../src/lib/accreditation/model.js'
import { PRESS_CAPACITY_DEFAULT } from '../../src/lib/accreditation/model.js'

export type StoreData = {
  seq: number
  pressCapacity: number
  items: Accreditation[]
}

function item(
  partial: Pick<Accreditation, 'reference' | 'status' | 'createdAt' | 'fullName' | 'mediaName' | 'role' | 'phone' | 'email' | 'cityCountry' | 'mediaType' | 'mediaLink' | 'teamSize' | 'teamMembers'> &
    Partial<Accreditation>,
): Accreditation {
  const createdAt = partial.createdAt
  return {
    id: partial.id || partial.reference.toLowerCase(),
    reference: partial.reference,
    status: partial.status,
    createdAt,
    updatedAt: partial.updatedAt || createdAt,
    fullName: partial.fullName,
    mediaName: partial.mediaName,
    role: partial.role,
    phone: partial.phone,
    email: partial.email,
    cityCountry: partial.cityCountry,
    mediaType: partial.mediaType,
    mediaTypeOther: partial.mediaTypeOther || '',
    mediaLink: partial.mediaLink,
    socialLinks: partial.socialLinks || '',
    coverageTypes: partial.coverageTypes || [],
    coverageProject: partial.coverageProject || '',
    interviews: partial.interviews || '',
    interviewPeople: partial.interviewPeople || [],
    teamSize: partial.teamSize,
    teamMembers: partial.teamMembers,
    gear: partial.gear || [],
    acceptAccuracy: partial.acceptAccuracy ?? true,
    acceptData: partial.acceptData ?? true,
    internalNotes: partial.internalNotes || '',
    complementFields: partial.complementFields || [],
    decisionMessage: partial.decisionMessage || '',
    refusalReason: partial.refusalReason || '',
    history: partial.history || [
      {
        at: createdAt,
        actor: 'Formulaire public',
        action: 'Demande envoyée',
        detail: 'Formulaire public',
      },
    ],
  }
}

/** Jeu de démonstration (noms fictifs) aligné sur les maquettes 23–26. */
export function buildSeed(): StoreData {
  return {
    seq: 129,
    pressCapacity: PRESS_CAPACITY_DEFAULT,
    items: [
      item({
        reference: 'AFA26-ACC-0129',
        status: 'nouvelle',
        createdAt: '2026-10-05T18:42:00+01:00',
        fullName: 'Aïcha Dossou',
        role: 'Rédactrice mode',
        mediaName: 'Bénin Mode Mag',
        mediaType: 'Média/page spécialisée mode',
        phone: '+229 01 97 45 12 30',
        email: 'aicha.dossou@beninmodemag.bj',
        cityCountry: 'Cotonou, Bénin',
        mediaLink: 'https://beninmodemag.bj',
        socialLinks: 'instagram.com/beninmodemag\ntiktok.com/@beninmodemag\nfacebook.com/beninmodemag',
        coverageTypes: ['Reportage', 'Interview', 'Photographie', 'Portraits/interviews finalistes'],
        coverageProject:
          'Dossier spécial « L’Ère des Audacieux » : reportage photo du tapis rouge, portraits de 5 finalistes et interviews publiées dans notre édition de décembre + stories en direct.',
        interviews: 'Oui',
        interviewPeople: ['Finalistes', 'Designers/stylistes', 'Organisateurs'],
        teamSize: '2',
        teamMembers: '1. Aïcha Dossou — Rédactrice mode\n2. Brice Tossou — Photographe',
        gear: ['Appareil photo', 'Smartphone', 'Microphone'],
        internalNotes:
          'Média sérieux, déjà présent en 2025. Vérifier que Brice Tossou n’est pas aussi déclaré chez un autre média.',
        history: [
          {
            at: '2026-10-05T18:42:00+01:00',
            actor: 'Formulaire public',
            action: 'Demande envoyée',
            detail: 'Formulaire public',
          },
        ],
      }),
      item({
        reference: 'AFA26-ACC-0128',
        status: 'nouvelle',
        createdAt: '2026-10-05T16:10:00+01:00',
        fullName: 'Koffi Mensah',
        role: 'Photographe',
        mediaName: 'Studio Lumière KM',
        mediaType: 'Photographe',
        phone: '+228 90 12 44 18',
        email: 'koffi@studiolumiere.tg',
        cityCountry: 'Lomé, Togo',
        mediaLink: 'https://studiolumiere.tg',
        socialLinks: 'instagram.com/studiolumiere.km',
        coverageTypes: ['Photographie', 'Portraits/interviews finalistes'],
        coverageProject: 'Portraits plateau et coulisses, série publiée sous 10 jours.',
        interviews: 'Non',
        teamSize: '1',
        teamMembers: '1. Koffi Mensah — Photographe',
        gear: ['Appareil photo', 'Éclairage'],
      }),
      item({
        reference: 'AFA26-ACC-0127',
        status: 'nouvelle',
        createdAt: '2026-10-05T11:03:00+01:00',
        fullName: 'Nadège Zinsou',
        role: 'Rédactrice en chef',
        mediaName: 'La Nation',
        mediaType: 'Presse écrite',
        phone: '+229 01 21 30 45 67',
        email: 'nadege.zinsou@lanation.bj',
        cityCountry: 'Cotonou, Bénin',
        mediaLink: 'https://lanation.bj',
        coverageTypes: ['Reportage', 'Interview'],
        coverageProject: 'Page culture du 16 novembre et entretien avec deux finalistes.',
        interviews: 'Oui',
        interviewPeople: ['Finalistes', 'Organisateurs'],
        teamSize: 'Plus de 4',
        teamMembers:
          '1. Nadège Zinsou — Rédactrice en chef\n2. Marc Houngbédji — Journaliste\n3. Sonia Akakpo — Photographe\n4. Yves Dossou — Photographe\n5. Lara Gomez — Stagiaire',
        gear: ['Appareil photo', 'Microphone', 'Smartphone'],
      }),
      item({
        reference: 'AFA26-ACC-0126',
        status: 'approuvee',
        createdAt: '2026-10-04T09:27:00+01:00',
        updatedAt: '2026-10-04T15:10:00+01:00',
        fullName: 'Fatou Ndiaye',
        role: 'Journaliste',
        mediaName: 'Canal Afrique TV',
        mediaType: 'Télévision',
        phone: '+221 77 123 45 67',
        email: 'fatou.ndiaye@canalafrique.tv',
        cityCountry: 'Dakar, Sénégal',
        mediaLink: 'https://canalafrique.tv',
        coverageTypes: ['Reportage', 'Interview', 'Vidéo', 'Live'],
        coverageProject: 'Sujet JT de 3 minutes et live du tapis rouge.',
        interviews: 'Oui',
        interviewPeople: ['Designers/stylistes', 'Personnalités/invités'],
        teamSize: '3',
        teamMembers:
          '1. Fatou Ndiaye — Journaliste\n2. Ibrahima Sarr — Cadreur\n3. Awa Diop — Preneuse de son',
        gear: ['Caméra vidéo', 'Microphone', 'Trépied', 'Éclairage'],
        decisionMessage:
          'Bonjour Fatou, votre accréditation pour les Africa Fashion Awards 2026 est confirmée (3 personnes).',
        history: [
          {
            at: '2026-10-04T09:27:00+01:00',
            actor: 'Formulaire public',
            action: 'Demande envoyée',
            detail: 'Formulaire public',
          },
          {
            at: '2026-10-04T15:10:00+01:00',
            actor: 'Gauthier ORE',
            action: 'Demande approuvée',
            detail: '3 badges nominatifs',
          },
        ],
      }),
      item({
        reference: 'AFA26-ACC-0125',
        status: 'complement',
        createdAt: '2026-10-03T20:15:00+01:00',
        updatedAt: '2026-10-04T08:40:00+01:00',
        fullName: 'Rodrigue Agbo',
        role: 'Vidéaste',
        mediaName: 'RA Films',
        mediaType: 'Vidéaste',
        phone: '+229 01 66 20 18 44',
        email: 'rodrigue@rafilms.bj',
        cityCountry: 'Porto-Novo, Bénin',
        mediaLink: 'https://rafilms.bj',
        coverageTypes: ['Vidéo', 'Couverture réseaux sociaux', 'Live'],
        coverageProject: 'Aftermovie et couvertures stories.',
        interviews: 'À confirmer',
        interviewPeople: ['Designers/stylistes'],
        teamSize: '2',
        teamMembers: '1. Rodrigue Agbo — Vidéaste\n2. Brice Tossou — Assistant image',
        gear: ['Caméra vidéo', 'Stabilisateur/Gimbal', 'Smartphone'],
        complementFields: ['11. Projet de couverture', '15. Noms et fonctions de l’équipe'],
        decisionMessage:
          'Bonjour Rodrigue, merci de préciser vos dates de publication et la fonction exacte de chaque membre de l’équipe.',
        internalNotes: 'Après-movie intéressant. Équipe à confirmer avant badge.',
        history: [
          {
            at: '2026-10-03T20:15:00+01:00',
            actor: 'Formulaire public',
            action: 'Demande envoyée',
            detail: 'Formulaire public',
          },
          {
            at: '2026-10-04T08:40:00+01:00',
            actor: 'Gauthier ORE',
            action: 'Complément demandé',
            detail: 'Projet de couverture, noms et fonctions',
          },
        ],
      }),
      item({
        reference: 'AFA26-ACC-0124',
        status: 'approuvee',
        createdAt: '2026-10-03T14:51:00+01:00',
        updatedAt: '2026-10-03T18:05:00+01:00',
        fullName: 'Mireille Houngbo',
        role: 'Créatrice de contenu',
        mediaName: '@mireille.style',
        mediaType: 'Créateur de contenu',
        phone: '+229 01 97 11 22 33',
        email: 'mireille.houngbo@gmail.com',
        cityCountry: 'Cotonou, Bénin',
        mediaLink: 'https://instagram.com/mireille.style',
        socialLinks: 'instagram.com/mireille.style\ntiktok.com/@mireille.style',
        coverageTypes: ['Couverture réseaux sociaux', 'Live', 'Photographie'],
        coverageProject: 'Stories et un reel récapitulatif le soir même.',
        interviews: 'Non',
        teamSize: '1',
        teamMembers: '1. Mireille Houngbo — Créatrice de contenu',
        gear: ['Smartphone'],
        history: [
          {
            at: '2026-10-03T14:51:00+01:00',
            actor: 'Formulaire public',
            action: 'Demande envoyée',
            detail: 'Formulaire public',
          },
          {
            at: '2026-10-03T18:05:00+01:00',
            actor: 'Gauthier ORE',
            action: 'Demande approuvée',
            detail: '1 badge nominatif',
          },
        ],
      }),
      item({
        reference: 'AFA26-ACC-0123',
        status: 'refusee',
        createdAt: '2026-10-02T10:38:00+01:00',
        updatedAt: '2026-10-02T17:20:00+01:00',
        fullName: 'Serge Kouassi',
        role: 'Animateur',
        mediaName: 'Radio Planète FM',
        mediaType: 'Radio',
        phone: '+225 07 00 11 22 33',
        email: 'serge.kouassi@planetefm.ci',
        cityCountry: 'Abidjan, Côte d’Ivoire',
        mediaLink: 'https://planetefm.example',
        coverageTypes: ['Interview', 'Live'],
        coverageProject: 'Plateau radio délocalisé.',
        interviews: 'Oui',
        interviewPeople: ['Personnalités/invités'],
        teamSize: '2',
        teamMembers: '1. Serge Kouassi — Animateur\n2. Paul Koffi — Technicien',
        gear: ['Microphone'],
        refusalReason: 'lien',
        decisionMessage:
          'Bonjour, nous n’avons pas pu vérifier le lien média communiqué. Nous ne pouvons donc pas donner suite à votre demande pour cette édition.',
        history: [
          {
            at: '2026-10-02T10:38:00+01:00',
            actor: 'Formulaire public',
            action: 'Demande envoyée',
            detail: 'Formulaire public',
          },
          {
            at: '2026-10-02T17:20:00+01:00',
            actor: 'Gauthier ORE',
            action: 'Demande refusée',
            detail: 'Lien média non vérifiable',
          },
        ],
      }),
      item({
        reference: 'AFA26-ACC-0122',
        status: 'nouvelle',
        createdAt: '2026-10-01T22:04:00+01:00',
        fullName: 'Yann Ahouansou',
        role: 'Influenceur',
        mediaName: '@yann.ahs',
        mediaType: 'Influenceur',
        phone: '+229 01 96 00 12 12',
        email: 'yann.ahouansou@gmail.com',
        cityCountry: 'Cotonou, Bénin',
        mediaLink: 'https://instagram.com/yann.ahs',
        socialLinks: 'instagram.com/yann.ahs\ntiktok.com/@yann.ahs',
        coverageTypes: ['Couverture réseaux sociaux', 'Live'],
        coverageProject: 'Couverture du tapis rouge en stories.',
        interviews: 'À confirmer',
        teamSize: '1',
        teamMembers: '1. Yann Ahouansou — Influenceur',
        gear: ['Smartphone'],
      }),
    ],
  }
}
